### ISSUE TITLE
abaco init error tr: range-endpoints of '_-]' are in reverse collating sequence order

### ISSUE THREAD

**Issue by tcmitchell** [johnfonner/abaco-cli#8]
There is an error in the `slugify` function when running on Ubuntu 18:

```
$ abaco init -n my-new-reactor
tr: range-endpoints of '_-]' are in reverse collating sequence order
[INFO] Making project name URL safe: 
mkdir: cannot create directory ‘’: No such file or directory
[INFO] Defaulting to Python 3.6
cp: cannot create directory '/python3': Permission denied
/home/tommy/sd2/sd2e-cloud-cli/bin/abaco-init.sh: line 113: /reactor.rc: Permission denied
```

The `tr` error (first line of output above) causes the whole thing to go off the rails. Looking at the `tr` invocation in `slugify`:

```
tr -c -d [0-9A-Za-z\ _-]
```

I think there may be a quoting/escaping problem. The above works on macOS Mojave, but fails on Ubuntu 18. Here is just that part on Ubuntu 18:

```
$ echo 'my-new-reactor' | tr -c -d [0-9A-Za-z\ _-]
tr: range-endpoints of '_-]' are in reverse collating sequence order
```

Escaping the hyphen appears to work on both Ubuntu 18 and macOS Mojave:

```
$ echo 'my-new-reactor' | tr -c -d [0-9A-Za-z\ _\\-]
my-new-reactor
```

I don't know if this fix will work on other platforms in active use for abaco development. There also might be a better way to fix it. This worked for me.

**Comment by johnfonner** [comment]
Thanks for reporting this and for the suggested fix.  If that syntax actually works across all distributions, then I tip my hat to you, sir.  We re-implemented slugify in Python to sidestep the distribution specific behavior of `tr`.  The updated version was languishing in the dev branch of tacc-cloud/abaco-cli.  I merged it into master with a few other fixes just now.  Also, I enabled issues on that repo.  Let us know if you run into other issues.

Thanks!
Fonner
